version: 2
jobs:
  build:
    working_directory: ~/dist
    docker:
      - image: circleci/node:10.12.0
    steps:
      - checkout
  deploy:
    working_directory: ~/dist
    docker:
      - image: google/cloud-sdk:217.0.0-alpine
    steps:
      - checkout
      - run: apk add --no-cache nodejs npm yarn
      - run: yarn
      - run: yarn build
      - run: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
      - run: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - run: gcloud app deploy --quiet --project protein-counter-app

workflows:
  version: 2
  main:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
